"""
Problem Service — Implements the problem_selector skill algorithm.
Handles weak-area detection, difficulty calibration, spaced repetition, and recency bias.
The selection reason is generated by the Hermes Agent using the problem_selector skill.
"""
import json
import random
import logging
from datetime import datetime, timedelta
from typing import Optional

from sqlalchemy import select, func, or_
from sqlalchemy.ext.asyncio import AsyncSession

from backend.models.problem import Problem
from backend.models.session import Session
from backend.models.user import User
from backend.models.skill import UserTopicStat, SkillVersion
from backend.schemas.problem import TodayProblemResponse
from backend.services import hermes_agent

logger = logging.getLogger(__name__)

# Topics in the system
ALL_TOPICS = [
    "arrays", "linkedlists", "stacks", "trees", "graphs", "dp",
    "binarysearch", "heaps", "backtracking", "greedy", "tries", "bitmanip",
    "backend", "frontend", "fullstack", "web", "aiml", "data",
    "opensource", "systemdesign", "databases", "security",
]


async def select_todays_problem(
    user_id: str,
    db: AsyncSession,
    requested_topic: Optional[str] = None,
    requested_difficulty: Optional[str] = None,
) -> TodayProblemResponse:
    """
    Main problem selection algorithm — implements the problem_selector skill.

    Steps:
    1. Identify focus area (lowest score, least recent)
    2. Determine difficulty (based on recent performance)
    3. Apply spaced repetition (check review dates)
    4. Select unseen or due-for-review problem
    """
    # Get user
    user_result = await db.execute(select(User).where(User.id == user_id))
    user = user_result.scalar_one_or_none()
    if not user:
        raise ValueError("User not found")

    # Get current skill version
    skill_result = await db.execute(
        select(SkillVersion)
        .where(SkillVersion.skill_name == "problem_selector")
        .order_by(SkillVersion.created_at.desc())
    )
    skill = skill_result.scalars().first()
    skill_version = skill.version if skill else "1.0"

    # Get topic stats
    stats_result = await db.execute(
        select(UserTopicStat).where(UserTopicStat.user_id == user_id)
    )
    topic_stats = {s.topic: s for s in stats_result.scalars().all()}

    # Get recent sessions (last 10)
    sessions_result = await db.execute(
        select(Session)
        .where(Session.user_id == user_id)
        .order_by(Session.created_at.desc())
        .limit(10)
    )
    recent_sessions = sessions_result.scalars().all()

    # Get seen problem IDs (last 7 days)
    week_ago = datetime.utcnow() - timedelta(days=7)
    seen_result = await db.execute(
        select(Session.problem_id)
        .where(Session.user_id == user_id, Session.created_at >= week_ago)
    )
    seen_ids = {r[0] for r in seen_result.all()}

    # ─── Step 1: Identify focus area ──────────────────────────────────
    if requested_topic:
        focus_topic = requested_topic
        reason = f"You requested a {requested_topic} problem."
    else:
        focus_topic, reason = _identify_focus_area(topic_stats, recent_sessions)

    # ─── Step 2: Determine difficulty ─────────────────────────────────
    if requested_difficulty:
        target_difficulty = requested_difficulty
    else:
        target_difficulty = _determine_difficulty(focus_topic, topic_stats, recent_sessions)

    # ─── Step 3: Select problem ───────────────────────────────────────
    # Try: matching topic + difficulty, not seen recently
    query = select(Problem).where(
        Problem.topic == focus_topic,
        Problem.difficulty == target_difficulty,
        or_(Problem.owner_user_id.is_(None), Problem.owner_user_id == user_id),
        ~Problem.id.in_(seen_ids) if seen_ids else True,
    )
    result = await db.execute(query)
    candidates = result.scalars().all()

    # Fallback: any difficulty in same topic
    if not candidates:
        query = select(Problem).where(
            Problem.topic == focus_topic,
            or_(Problem.owner_user_id.is_(None), Problem.owner_user_id == user_id),
            ~Problem.id.in_(seen_ids) if seen_ids else True,
        )
        result = await db.execute(query)
        candidates = result.scalars().all()

    # Fallback: any topic
    if not candidates:
        query = select(Problem).where(
            or_(Problem.owner_user_id.is_(None), Problem.owner_user_id == user_id),
            ~Problem.id.in_(seen_ids) if seen_ids else True,
        )
        result = await db.execute(query)
        candidates = result.scalars().all()

    # Final fallback: any problem
    if not candidates:
        result = await db.execute(
            select(Problem).where(or_(Problem.owner_user_id.is_(None), Problem.owner_user_id == user_id))
        )
        candidates = result.scalars().all()

    if not candidates:
        raise ValueError("No problems available in the bank")

    problem = random.choice(candidates)

    # Estimate time
    time_map = {"easy": "15-20", "medium": "30-40", "hard": "45-60"}
    est_minutes = time_map.get(problem.difficulty, "30-40")

    # Ask Hermes Agent to generate a personalized selection reason
    # The agent uses the problem_selector skill file as its system prompt
    hermes_reason = await hermes_agent.generate_selection_reason(
        user, problem, topic_stats, db
    )
    if hermes_reason:
        reason = hermes_reason

    return TodayProblemResponse(
        id=problem.id,
        title=problem.title,
        slug=problem.slug,
        difficulty=problem.difficulty,
        topic=problem.topic,
        sub_topic=problem.sub_topic,
        description=problem.description,
        estimated_minutes=est_minutes,
        selection_reason=reason,
        selected_by_skill_version=skill_version,
        hints=json.loads(problem.hints) if problem.hints else [],
    )


def _identify_focus_area(
    topic_stats: dict[str, UserTopicStat],
    recent_sessions: list[Session],
) -> tuple[str, str]:
    """Find the topic the user should focus on today."""
    # Step 1a: Topics with score < 60
    weak_topics = [
        (topic, stat) for topic, stat in topic_stats.items()
        if stat.average_score < 60 and stat.attempts > 0
    ]

    if weak_topics:
        # Apply recency bias: prefer topics not practiced in 3+ days
        three_days_ago = datetime.utcnow() - timedelta(days=3)
        stale_weak = [
            (t, s) for t, s in weak_topics
            if s.last_practiced is None or s.last_practiced < three_days_ago
        ]
        if stale_weak:
            chosen = min(stale_weak, key=lambda x: x[1].average_score)
            return chosen[0], f"Focusing on {chosen[0]} today. Your average score is {round(chosen[1].average_score)} — below the target of 60."

        chosen = min(weak_topics, key=lambda x: x[1].average_score)
        return chosen[0], f"Focusing on {chosen[0]} today. Your score dropped to {round(chosen[1].average_score)} recently."

    # Step 1b: Topics with fewest recent attempts
    attempted_topics = set()
    for s in recent_sessions:
        pass  # Would need to join problem data

    # Fallback: least-practiced topic
    if topic_stats:
        least = min(topic_stats.values(), key=lambda s: s.attempts)
        return least.topic, f"Practicing {least.topic} — you've only attempted {least.attempts} problems here."

    # Random topic if no stats at all
    topic = random.choice(ALL_TOPICS)
    return topic, f"Starting with {topic}. Your first problem in this area!"


def _determine_difficulty(
    topic: str,
    topic_stats: dict[str, UserTopicStat],
    recent_sessions: list[Session],
) -> str:
    """Calibrate difficulty based on recent performance."""
    stat = topic_stats.get(topic)
    if not stat:
        return "easy"

    # Get recent scores for this topic
    recent_scores = []
    for s in recent_sessions:
        if s.score is not None:
            recent_scores.append(s.score)

    if len(recent_scores) >= 3:
        last_3 = recent_scores[:3]
        if all(s > 80 for s in last_3):
            # Step up
            return {"easy": "medium", "medium": "hard", "hard": "hard"}.get(stat.current_difficulty, "hard")
        if all(s < 50 for s in last_3[:2]):
            # Step down
            return {"easy": "easy", "medium": "easy", "hard": "medium"}.get(stat.current_difficulty, "easy")

    return stat.current_difficulty or "easy"
